import Link from "next/link";
import { ArrowRight, CreditCard, LifeBuoy } from "lucide-react";
import { PublicPage, StatePage, SupportCard } from "@/components/site-pages";

export function BillingPage({ mode = "billing" }: { mode?: "billing" | "upgrade" | "downgrade" | "cancel" }) {
  const copy = { billing: ["Billing", "Manage your MUN Prep access and payment history.", "Your access is controlled by verified payment status and the current entitlement on your account."], upgrade: ["Upgrade", "Choose a larger preparation workspace.", "Review available plans and start a verified payment from the access page. Your existing entitlement is checked before a new purchase."], downgrade: ["Downgrade", "Plan changes should be deliberate.", "MUN Prep currently uses time-based access plans. Contact support with your account email and preferred plan so the change can be reviewed without interrupting valid access."], cancel: ["Cancel subscription", "Tell us when you want access to stop renewing.", "Submit a cancellation request through support with your account email and plan. Cancellation does not automatically reverse a completed paid period."] }[mode];
  return <PublicPage><section className="mx-auto max-w-3xl px-5 py-16 sm:px-8"><p className="label-text text-[var(--oxblood)]">Account lifecycle</p><h1 className="display-type mt-3 text-5xl">{copy[0]}</h1><p className="mt-5 text-lg leading-8 text-[var(--muted)]">{copy[1]}</p><div className="surface mt-8 rounded-2xl p-6 sm:p-8"><CreditCard className="h-7 w-7 text-[var(--patina)]" aria-hidden="true" /><p className="mt-4 leading-7 text-[var(--muted)]">{copy[2]}</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/pricing" className="button-primary inline-flex items-center gap-2 px-4 font-semibold">View access <ArrowRight className="h-4 w-4" /></Link><Link href="/support" className="button-secondary inline-flex px-4 font-semibold">Contact support</Link></div></div></section></PublicPage>;
}

export function SupportPage() { return <PublicPage><section className="mx-auto max-w-4xl px-5 py-16 sm:px-8"><p className="label-text text-[var(--oxblood)]">Support</p><h1 className="display-type mt-3 text-5xl sm:text-7xl">Help when the room gets busy.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--muted)]">Find guidance for account access, payments, AI workspace issues, referrals, certificates, and accessibility.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><SupportCard /><div className="surface rounded-2xl p-6"><h2 className="display-type text-2xl">What to include</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Share the page, approximate time, device/browser, order reference if relevant, and the exact error message. Never send passwords, API keys, or full payment credentials.</p></div></div></section></PublicPage>; }

export function HelpCenterPage() { return <PublicPage><section className="mx-auto max-w-4xl px-5 py-16 sm:px-8"><p className="label-text text-[var(--oxblood)]">Help center</p><h1 className="display-type mt-3 text-5xl">Start with the basics.</h1><div className="mt-10 grid gap-3 sm:grid-cols-2">{[["Account access", "/login"], ["Reset password", "/auth/forgot-password"], ["Payment status", "/checkout/pending"], ["Course certificates", "/app/courses"], ["Privacy and policies", "/legal"], ["Contact support", "/support"]].map(([label, href]) => <Link key={href} href={href} className="surface rounded-xl p-5 font-bold transition hover:-translate-y-0.5 hover:border-[var(--patina)]">{label}<span className="mt-2 block text-sm font-normal text-[var(--muted)]">Open guidance →</span></Link>)}</div></section></PublicPage>; }

export function LifecycleState({ kind }: { kind: "pending" | "failed" | "success" | "offline" | "maintenance" | "session" | "empty" | "search" | "loading" | "error" | "forbidden" | "not-found" | "server-error" }) {
  const states = { pending: ["…", "Payment is being verified", "Keep this page open while the payment provider confirms the result."], failed: ["!", "Payment could not be confirmed", "No premium access was granted from this attempt. You can return to access and try again."], success: ["✓", "Payment confirmed", "Your verified access is ready. Return to the dashboard to begin."], offline: ["⌁", "You appear to be offline", "Reconnect to the internet and try again. Your saved work remains tied to your account."], maintenance: ["—", "MUN Prep is taking a short pause", "Please try again soon. We are keeping the workspace safe while maintenance is in progress."], session: ["↗", "Your session expired", "Sign in again to continue securely."], empty: ["∅", "Nothing here yet", "Once you create or save something, it will appear in this space."], search: ["?", "No results found", "Try a shorter search or a different phrase."], loading: ["…", "Loading", "We are preparing this space for you."], error: ["!", "Something went wrong", "Please try again. If the issue continues, contact support with the page and error message."], forbidden: ["403", "Access denied", "You do not have permission to view this space."], "not-found": ["404", "Page not found", "The page may have moved, or the link may be outdated."], "server-error": ["500", "The server hit a problem", "Please try again in a moment. If it continues, contact support."] }[kind];
  const action = kind === "session" ? <Link href="/login" className="button-primary inline-flex px-5 font-semibold">Sign in again</Link> : kind === "failed" ? <Link href="/pricing" className="button-primary inline-flex px-5 font-semibold">Return to access</Link> : <Link href="/" className="button-secondary inline-flex px-5 font-semibold">Back home</Link>;
  return <StatePage code={states[0]} title={states[1]} description={states[2]} action={action} />;
}
