export type SitePage = {
  title: string;
  eyebrow: string;
  description: string;
  sections: Array<{ heading: string; body: string }>;
};

const legalNote = "Working draft for MUN Prep. This page is not legal advice and should be reviewed by a qualified lawyer before publication or reliance. Replace business identity, jurisdiction, contact, retention, and payment details with your approved terms.";

export const legalPages: Record<string, SitePage> = {
  "privacy-policy": { title: "Privacy Policy", eyebrow: "Legal", description: "How MUN Prep collects, uses, stores, and protects account and workspace information.", sections: [{ heading: "Information we collect", body: "MUN Prep may collect account identifiers, profile details, workspace inputs, saved chats, course progress, payment references, and technical information needed to operate the service. Payment credentials should be handled by the payment provider rather than stored by MUN Prep." }, { heading: "How we use information", body: "We use information to authenticate users, provide the delegate workspace, save progress, process access entitlements, prevent abuse, support users, and improve reliability. AI requests may be sent to the configured model provider to produce the requested output." }, { heading: "Storage and retention", body: "Account, progress, and saved workspace data are retained while needed to provide the service or meet legal and operational obligations. Users may request access, correction, or deletion through support, subject to lawful exceptions." }, { heading: "Contact and review", body: legalNote }] },
  "terms-of-service": { title: "Terms of Service", eyebrow: "Legal", description: "The rules for using the MUN Prep delegate preparation workspace.", sections: [{ heading: "Using the service", body: "You must provide accurate account information, keep your credentials secure, and use MUN Prep lawfully. You are responsible for reviewing generated material before using it in a conference, submission, speech, or other consequential setting." }, { heading: "AI-generated material", body: "MUN Prep provides preparation assistance, not guaranteed factual, legal, diplomatic, or academic conclusions. Verify current events, quotations, statistics, citations, and policy positions independently." }, { heading: "Payments and access", body: "Paid access is activated only after the payment system verifies a successful payment. Access may expire according to the selected plan. Nothing on a success page replaces server-side payment verification." }, { heading: "Review note", body: legalNote }] },
  "cookie-policy": { title: "Cookie Policy", eyebrow: "Legal", description: "A plain-language explanation of cookies and browser storage used by MUN Prep.", sections: [{ heading: "Essential cookies", body: "MUN Prep uses essential session and security cookies to keep users signed in, protect administrative routes, and remember first-touch referral attribution when a referral link is used." }, { heading: "Preferences", body: "Optional preferences may be stored locally in your browser to remember choices such as cookie settings. Disabling essential cookies may prevent authentication or secure workspace features from working." }, { heading: "Managing cookies", body: "You can clear cookies through your browser settings. When available, use Cookie Preferences to control optional storage without disabling essential security cookies." }, { heading: "Review note", body: legalNote }] },
  "cookie-preferences": { title: "Cookie Preferences", eyebrow: "Privacy controls", description: "Choose whether MUN Prep may use optional browser storage beyond essential security and session functions.", sections: [{ heading: "Your current choice", body: "Essential cookies remain enabled because they are needed for secure sign-in and core navigation. Optional analytics or preference storage can be changed below." }, { heading: "What this does", body: "Your choice is saved in this browser. It does not delete information already stored by third-party providers, and it does not change essential authentication or payment cookies." }] },
  "refund-policy": { title: "Refund Policy", eyebrow: "Legal", description: "How refund requests for paid MUN Prep access are reviewed.", sections: [{ heading: "Requesting a refund", body: "Contact support with the account email, order reference, payment date, and a short explanation. Do not send full card numbers or secret payment credentials." }, { heading: "Review", body: "Refund eligibility depends on the applicable purchase terms, payment status, access usage, and applicable consumer law. A payment that is pending or failed is not treated as a completed purchase." }, { heading: "Processing", body: "Approved refunds are returned through the original payment channel where supported. Processing times can depend on the payment provider or bank." }, { heading: "Review note", body: legalNote }] },
  "cancellation-policy": { title: "Cancellation Policy", eyebrow: "Legal", description: "What happens when a user stops a recurring or time-limited MUN Prep plan.", sections: [{ heading: "Cancellation", body: "Cancellation requests should be submitted through the available account or support flow. Cancellation stops future renewal where recurring billing is enabled; it does not necessarily reverse access already granted for a completed paid period." }, { heading: "Access after cancellation", body: "Unless applicable terms say otherwise, access remains available until the current entitlement expires. Server-side entitlement status is authoritative." }, { heading: "Review note", body: legalNote }] },
  "shipping-policy": { title: "Shipping Policy", eyebrow: "Legal", description: "MUN Prep is a digital service and does not normally ship physical goods.", sections: [{ heading: "Digital delivery", body: "Paid access is delivered electronically after verified payment and entitlement activation. No physical shipment, tracking number, or shipping address is required for ordinary MUN Prep plans." }, { heading: "Review note", body: legalNote }] },
  "return-exchange-policy": { title: "Return / Exchange Policy", eyebrow: "Legal", description: "MUN Prep access is digital, so physical returns and exchanges generally do not apply.", sections: [{ heading: "Digital access", body: "Because MUN Prep provides a digital workspace, physical returns are not applicable. If access is not activated after a verified payment, contact support with the order reference so the account can be reviewed." }, { heading: "Review note", body: legalNote }] },
  disclaimer: { title: "Disclaimer", eyebrow: "Legal", description: "Important limits on MUN Prep content and AI-assisted preparation.", sections: [{ heading: "Preparation tool", body: "MUN Prep is an educational preparation tool. Generated content may contain mistakes, omissions, outdated information, or contested interpretations. Verify important claims against reliable primary sources and current official materials." }, { heading: "No professional advice", body: "MUN Prep does not provide legal, financial, medical, immigration, diplomatic, or other professional advice. Use appropriate qualified professionals when a matter requires it." }, { heading: "Review note", body: legalNote }] },
  "accessibility-statement": { title: "Accessibility Statement", eyebrow: "Legal", description: "Our commitment to making MUN Prep usable across devices, browsers, and assistive technologies.", sections: [{ heading: "Our goal", body: "We aim to provide clear structure, keyboard-accessible controls, visible focus states, readable contrast, responsive layouts, and text alternatives for meaningful interface content." }, { heading: "Feedback", body: "If you encounter an accessibility barrier, contact support with the page, device, browser, and a description of what went wrong. Feedback helps us prioritize fixes." }, { heading: "Review note", body: legalNote }] },
  "data-processing-agreement": { title: "Data Processing Agreement", eyebrow: "Legal", description: "A framework for processing personal data on behalf of organizations using MUN Prep.", sections: [{ heading: "Scope", body: "This draft describes processor responsibilities for personal data handled through the MUN Prep service where a customer acts as controller or equivalent decision-maker." }, { heading: "Security and subprocessors", body: "Processing should be limited to documented service purposes, with appropriate access controls, provider safeguards, incident handling, and deletion or return procedures." }, { heading: "Review note", body: legalNote }] },
  "acceptable-use-policy": { title: "Acceptable Use Policy", eyebrow: "Legal", description: "Uses that are allowed and prohibited on MUN Prep.", sections: [{ heading: "Allowed use", body: "Use MUN Prep for lawful Model UN research, writing practice, learning, collaboration, and personal preparation." }, { heading: "Prohibited use", body: "Do not misuse the service to attack systems, bypass access controls, abuse payment flows, upload unlawful material, impersonate others, harass users, or generate content intended to facilitate wrongdoing." }, { heading: "Enforcement", body: "We may limit, suspend, or terminate access where necessary to protect users, the service, providers, or legal obligations." }, { heading: "Review note", body: legalNote }] },
  "security-policy": { title: "Security Policy", eyebrow: "Legal", description: "The security principles used to protect MUN Prep accounts, data, payments, and integrations.", sections: [{ heading: "Controls", body: "MUN Prep uses server-side secret handling, authenticated API routes, protected admin sessions, row-level security, payment verification, rate limiting, and security headers as appropriate to the service architecture." }, { heading: "Account safety", body: "Use a unique password, avoid sharing credentials, and report suspicious activity promptly. MUN Prep personnel should never ask for a provider API key in ordinary support messages." }, { heading: "Review note", body: legalNote }] },
  "responsible-disclosure": { title: "Responsible Disclosure", eyebrow: "Security", description: "How to report a suspected security vulnerability responsibly.", sections: [{ heading: "Report privately", body: "Send a clear report through the approved support or security contact. Include the affected URL, reproduction steps, impact, and any safe proof of concept. Do not access, modify, or download other users’ data." }, { heading: "Please avoid", body: "Do not perform denial-of-service testing, social engineering, credential attacks, destructive actions, or public disclosure before the issue is reviewed." }, { heading: "Response", body: "We will acknowledge reports when possible, investigate within a reasonable period, and coordinate remediation or disclosure where appropriate." }, { heading: "Review note", body: legalNote }] },
  "community-guidelines": { title: "Community Guidelines", eyebrow: "Legal", description: "The standards for respectful, constructive MUN Prep participation.", sections: [{ heading: "Be constructive", body: "Discuss ideas and policy positions without attacking people. Respect different backgrounds, countries, viewpoints, and experience levels." }, { heading: "Protect privacy", body: "Do not post passwords, private contact information, payment credentials, or another person’s personal data." }, { heading: "Report problems", body: "Report harassment, abuse, impersonation, or unsafe content through support so it can be reviewed." }, { heading: "Review note", body: legalNote }] },
};

export const legalSlugs = Object.keys(legalPages);
